### ISSUE TITLE
An error occurred while resolving packages:   Project has invalid dependencies:     com.atteneder.draco: Error when executing git command. git-lfs filter-process: git-lfs: command not found     fatal: the remote end hung up unexpectedly     warning: Clone succeeded, but checkout failed.     You can inspect what was checked out with 'git status'     and retry the checkout with 'git checkout -f HEAD'

### ISSUE THREAD

**Issue by morty346** [atteneder/DracoUnityDemo#1]
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.atteneder.draco: Error when executing git command. git-lfs filter-process: git-lfs: command not found
    fatal: the remote end hung up unexpectedly
    warning: Clone succeeded, but checkout failed.
    You can inspect what was checked out with 'git status'
    and retry the checkout with 'git checkout -f HEAD'

**Comment by atteneder** [comment]
Please install and get familiar with [GIT LFS](https://git-lfs.github.com/). It's required for using this repository, otherwise the binary libraries will not get cloned properly.
