### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by FanEric** [atteneder/DracoUnityDemo#2]
The demo ran failed.
Package installed from local
Has anyone ran the demo successfully?

**Comment by emrys95** [comment]
> The demo ran failed.
> Package installed from local
> Has anyone ran the demo successfully?

I don't think anyone's been able to run this without deviating from the written instructions.
The thing is pretty much set up already with nothing left to do except run it, and then it just doesn't work.  Halp!

**Comment by aashiqsworld** [comment]
I've tried this sample project, and I've also tried the script here with the updated package from the other repo. I always get "Failed: Decoding Error" whenever I press space. Hopefully we can get some info on this.

**Comment by Andorfy** [comment]
If you download the project as a zip file, the "bunny_norm.drc" in the StreamingAssets folder will be wrong (the size will be around 1kb). Download this file from the repo again, and overwrite the original in the project (the new file will be around 107 kb), then the demo will work.

**Comment by YeonduBori** [comment]
> If you download the project as a zip file, the "bunny_norm.drc" in the StreamingAssets folder will be wrong (the size will be around 1kb). Download this file from the repo again, and overwrite the original in the project (the new file will be around 107 kb), then the demo will work.

Thanks!!!! :) I fixed it Failed Decoding Error @Andorfy

**Comment by atteneder** [comment]
Sorry for the late reply.

Thanks @Andorfy for finding and providing a fix!

This project uses GIT LFS for binary files (like the .drc files). You have to have GIT LFS installed and setup when cloning. Apparently also the ZIP download is affected.

I'll keep this issue opened until a proper How-to is in the README file.

Thanks for pointing it out!

**Comment by hujinhan12** [comment]
I'm able to display the bunny.

However, the decoding error occurred if I change the file to a customized .drc file.

The customized .drc file is a .ply point cloud compressed in the c++ environment with the draco_encoder.

Please let me know if this draco unity plugin works on such compressed point clouds.

Thank you very much.

**Comment by atteneder** [comment]
> The customized .drc file is a .ply point cloud compressed in the c++ environment with the draco_encoder.
> 
> Please let me know if this draco unity plugin works on such compressed point clouds.
> 
> Thank you very much.

Points clouds are not supported yet.

However, there was [work done](https://github.com/atteneder/glTFast/issues/135) to bring it to 1.4.0 and I'll look into it for the upcoming 2.0 release soon (see [this issue](https://github.com/atteneder/DracoUnity/issues/16) )

**Comment by atteneder** [comment]
Original problem was solved
